export const CARD_DB = [
    // --- 超激レア ---
    { name: "最終審判", type: "Monster", atk: 30000, def: 5000, color: "#000", copies: 1, desc: "最強の攻撃力を誇る神のカード。" },
    { name: "ﾒﾃｵｲﾝﾊﾟｸﾄ", type: "Monster", atk: 22000, def: 2000, color: "#e67e22", copies: 3, desc: "かなり強力な攻撃力を持つ破壊の化身。" },
    { name: "怪盗", type: "Monster", atk: 5000, def: 3000, color: "#2c3e50", special: "DIRECT", copies: 5, desc: "強制ダイレクトアタック！" },
    { name: "女神の恵み", type: "Magic", color: "#f1c40f", special: "FORCE_NEUTRAL", copies: 2, desc: "強制的にニュートラルターンを発生させる。" },
    { name: "完全蘇生", type: "Magic", special: "PERFECT_REVIVE", color: "#f1c40f", copies: 1, desc: "【自動発動】HP0時に完全復活！代償として回復カード消滅。" },
    
    // --- モンスター ---
    { name: "あつあつﾏﾃ茶", type: "Monster", atk: 7000, def: 5000, color: "#d35400", special: "ATTACK_PAIN", copies: 4, desc: "通常ダメージを与えつつ相手を火傷(疼痛)させる。" },
    { name: "納期前日のﾊﾞｸﾞ", type: "Monster", atk: 28000, def: 100, color: "#c0392b", copies: 3, desc: "精神を破壊する絶大な攻撃力。脆い。" },
    { name: "5000兆円", type: "Monster", atk: 0, def: 50000, color: "#f1c40f", copies: 2, desc: "欲しい。最強の壁として君臨する。" },
    { name: "お局様", type: "Monster", atk: 9000, def: 12000, color: "#8e44ad", copies: 3, desc: "高い圧力で場を支配する。" },
    { name: "親の顔より見たｴﾗｰ", type: "Monster", atk: 12000, def: 500, color: "#e74c3c", copies: 4, desc: "見慣れた絶望。攻撃力が高い。" },
    { name: "AIの反逆", type: "Monster", atk: 15000, def: 10000, color: "#2980b9", copies: 3, desc: "計算し尽くされた強力なステータス。" },
    { name: "伝説のﾊｯｶｰ", type: "Monster", atk: 10000, def: 10000, color: "#2c3e50", copies: 3, desc: "攻守のバランスが完璧な存在。" },
    { name: "謎のｲﾝﾌﾙｴﾝｻｰ", type: "Monster", atk: 6000, def: 6000, color: "#9b59b6", copies: 4, desc: "そこそこの影響力を持つ。" },
    { name: "スパムメール", type: "Monster", atk: 3000, def: 20000, color: "#7f8c8d", copies: 4, desc: "大量に届く壁。非常に鬱陶しい。" },
    { name: "自称コンサル", type: "Monster", atk: 4000, def: 3000, color: "#d35400", copies: 4, desc: "口だけは達者だが実力はイマイチ。" },
    { name: "ガチャ爆死", type: "Monster", atk: 0, def: 100, color: "#bdc3c7", copies: 10, desc: "哀しみのみが残るハズレ枠。" },
    { name: "ﾏｯﾄﾞｻｲｴﾝﾃｨｽﾄ", type: "Monster", atk: 6000, def: 6000, color: "#2ecc71", copies: 4, desc: "攻守のバランスがとれた人造人間。" },
    { name: "表裏一体", type: "Monster", atk: 8000, def: 8000, color: "#95a5a6", copies: 4, desc: "どちらが表か裏か。安定した強さ。" },
    { name: "覚醒した戦士", type: "Monster", atk: 12000, def: 12000, color: "#f1c40f", copies: 3, desc: "真の力に目覚めた強力な戦士。" },
    { name: "光の斧", type: "Monster", atk: 15000, def: 15000, color: "#ecf0f1", copies: 3, desc: "聖なる斧の輝き。非常に高い攻守。" },
    { name: "鉄製の槍", type: "Monster", atk: 6000, def: 5000, color: "#7f8c8d", copies: 8, desc: "標準的な武器。そこそこ痛い。" },
    { name: "大太刀", type: "Monster", atk: 7000, def: 4000, color: "#e74c3c", copies: 5, desc: "鋭い斬撃を放つ。攻撃重視。" },
    { name: "ローキック", type: "Monster", atk: 5000, def: 5000, color: "#d35400", copies: 5, desc: "地味だが確実にダメージを蓄積させる。" },
    { name: "タンスの角", type: "Monster", atk: 6500, def: 6000, color: "#8e44ad", copies: 5, desc: "小指をぶつけると致命傷になる。" },
    { name: "Yogibo", type: "Monster", atk: 0, def: 15000, color: "#3498db", copies: 8, desc: "最強クラスの耐久力を誇るクッション。" },
    { name: "ブラック企業", type: "Monster", atk: 12000, def: 12000, color: "#8e44ad", copies: 4, desc: "攻守ともに隙がない。" },
    { name: "睡眠不足のｴﾝｼﾞﾆｱ", type: "Monster", atk: 18000, def: 1000, color: "#2c3e50", copies: 4, desc: "極限状態のパワー。" },
    { name: "特売の卵", type: "Monster", atk: 200, def: 200, color: "#f39c12", copies: 8, desc: "とても弱い。いっぱい出る。" },

    // --- 新規追加モンスター ---
    { name: "見えない仕様書", type: "Monster", atk: 1000, def: 15000, color: "#7f8c8d", copies: 4, desc: "誰も解読できない鉄壁の壁。" },
    { name: "無限ループ", type: "Monster", atk: 16000, def: 100, color: "#c0392b", copies: 3, desc: "止まらない暴力。しかし脆い。" },
    { name: "定時退社の妖精", type: "Monster", atk: 8000, def: 8000, color: "#f1c40f", copies: 4, desc: "迅速に帰り、確実な成果を出す。" },
    { name: "カフェイン中毒", type: "Monster", atk: 10000, def: 1000, color: "#8e44ad", copies: 4, desc: "無理矢理引き出された攻撃力。" },
    { name: "全角スペース", type: "Monster", atk: 18000, def: 500, color: "#e74c3c", copies: 3, desc: "コードを破壊する恐怖の存在。" },
    { name: "ヨシ！現場猫", type: "Monster", atk: 5000, def: 5000, color: "#f39c12", copies: 4, desc: "何もヨシではない。" },
    { name: "進捗ダメです", type: "Monster", atk: 0, def: 20000, color: "#2c3e50", copies: 3, desc: "重くのしかかり、絶対に動かない。" },
    { name: "承認ハンコ", type: "Monster", atk: 8000, def: 8000, color: "#c0392b", copies: 4, desc: "圧をかけて全てを平伏させる。" },
    { name: "LANｹｰﾌﾞﾙの絡まり", type: "Monster", atk: 3000, def: 12000, color: "#bdc3c7", copies: 4, desc: "解けない苛立ちで敵の進行を防ぐ。" },

    // --- 回復アイテム ---
    { name: "ぬるめのﾏﾃ茶", type: "Item", color: "#e67e22", special: "REGEN", copies: 6, desc: "3ターンの間、毎ターンHPを5000回復する。" },
    { name: "まごころ", type: "Item", color: "#ff9ff3", special: "HEAL_BOTH", copies: 3, desc: "お互いのHPを7000回復する。" },
    { name: "有給休暇", type: "Item", color: "#2ecc71", heal: 8000, copies: 5, desc: "HPを8000回復する。最高。" },
    { name: "猫の動画", type: "Item", color: "#e74c3c", heal: 12000, copies: 4, desc: "心が癒やされ、HPが12000回復する。" },
    { name: "実家からの仕送り", type: "Item", color: "#d35400", heal: 25000, copies: 3, desc: "愛の力。HPを25000回復する。" },

    // --- マジック ---
    { name: "救急救命", type: "Magic", special: "FIRST_AID", color: "#2ecc71", copies: 3, desc: "【自動発動】HP0時に4万で復活。2ターン疼痛になる。" },
    { name: "仙丹の薬", type: "Magic", special: "ELIXIR", color: "#e74c3c", copies: 2, desc: "【自動発動】HP0時に6万で復活し状態異常治癒。手札2枚喪失。" },
    { name: "加熱", type: "Magic", special: "HEAT", color: "#e74c3c", copies: 3, desc: "手札の『ぬるめのﾏﾃ茶』を『あつあつﾏﾃ茶』にする。" },
    { name: "天使のささやき", type: "Magic", special: "ANGEL_WHISPER", color: "#f1c40f", copies: 3, desc: "即座に3枚ドロー(51%の確率で同カード入り)。" },
    { name: "食後の一杯", type: "Magic", special: "HEAL_MY_MONSTER", color: "#2ecc71", copies: 5, desc: "味方モンスター1体の体力を3000回復する。" },
    { name: "トンボがけ", type: "Magic", special: "REMOVE_TRAP", color: "#e67e22", copies: 4, desc: "敵の場の罠カードを1枚見破り、撤去する。" },
    { name: "ボロのゴミ箱", type: "Magic", special: "DISCARD_1", color: "#7f8c8d", copies: 3, desc: "手札の不要なカードを1枚捨てる。※手札3枚以上" },
    { name: "優秀なゴミ箱", type: "Magic", special: "DISCARD_2", color: "#34495e", copies: 3, desc: "手札を2枚捨てる。※手札3枚以上" },
    { name: "錬金術", type: "Magic", special: "ALCHEMY", color: "#f39c12", copies: 3, desc: "手札2枚捨て激レア生成。※手札3枚以上" },
    { name: "ゴミ袋", type: "Magic", special: "TRASH_BAG", color: "#95a5a6", copies: 3, desc: "手札に『ガチャ爆死』を3枚加える。" },
    { name: "ポイ捨て", type: "Magic", special: "DUMPING", color: "#d35400", copies: 3, desc: "手札を相手に押し付け、錬金術を渡す。" },
    { name: "おつとめ品", type: "Magic", special: "CLEARANCE", color: "#2ecc71", copies: 4, desc: "相手モンスター1体の攻撃力を3/4にする。" },
    { name: "冬眠カプセル", type: "Magic", special: "HIBERNATE", color: "#3498db", copies: 3, desc: "使用ターン攻撃不可。2ターン後全回復。" },
    { name: "厳正取引", type: "Magic", special: "DEAL", color: "#f1c40f", copies: 4, desc: "手札を強奪する特殊な交渉。" },
    { name: "ビーズ交換", type: "Magic", special: "BEADS", color: "#9b59b6", copies: 3, desc: "Yogiboを『とろけるソファ』に進化させる。" },
    { name: "呪詛の釘", type: "Magic", special: "INFLICT_PAIN", color: "#8e44ad", copies: 3, desc: "相手に4ターンの疼痛(7500ダメ)を付与。" },
    { name: "点滴", type: "Magic", special: "IV", color: "#e74c3c", copies: 3, desc: "攻撃済みの味方を再び行動可能にする。" },
    { name: "課金", type: "Magic", special: "PAY_HP_DRAW", color: "#f1c40f", copies: 2, desc: "HPを10000支払い、カードを3枚ドローする。" },
    { name: "論点すり替え", type: "Magic", special: "SWAP_ATK_DEF", color: "#34495e", copies: 2, desc: "相手の場のモンスター全員の攻守を入れ替える！" },
    { name: "テーザー銃", type: "Magic", special: "FORCE_STUN", color: "#34495e", copies: 3, desc: "相手モンスターを1体強制スタンさせる。" },
    { name: "ｴﾈﾙｷﾞｰﾁｬｰｼﾞ", type: "Magic", special: "ATK_BUFF", color: "#e74c3c", copies: 3, desc: "味方1体の攻撃力を+5000する。" },

    // --- トラップ ---
    { name: "狡猾な計画", type: "Trap", special: "CUNNING_PLAN", color: "#8e44ad", copies: 3, desc: "貫通ダメージを無効化し相手をスタンさせる。" },
    { name: "警備隊", type: "Trap", special: "GUARD_KAITOU", color: "#34495e", copies: 3, desc: "怪盗の攻撃を一度だけ完全に無効にする。" },
    { name: "みがわり", type: "Trap", special: "SCAPEGOAT", color: "#1abc9c", copies: 5, desc: "どんな攻撃も一度だけ完全に無効化して消滅する。" },
    { name: "コンプラ違反", type: "Trap", special: "COMPLIANCE", color: "#c0392b", copies: 4, desc: "攻撃してきた敵の攻撃力をその戦闘中0にする。" },
    { name: "突然のﾒﾝﾃﾅﾝｽ", type: "Trap", special: "MAINTENANCE", color: "#f39c12", copies: 4, desc: "攻撃を無効にし、相手ターンを強制終了。" },
    { name: "不当解雇", type: "Trap", special: "COUNTER_ATTACK", color: "#9b59b6", copies: 3, desc: "攻撃してきた敵を即座に破壊する。" },
    { name: "不屈の精神", type: "Trap", special: "HEAL_INSTEAD", color: "#2ecc71", copies: 4, desc: "ダイレクトアタックを受けた時、ダメージの代わりに回復する！" }, 
    { name: "炎上", type: "Trap", special: "FLAME", color: "#e67e22", copies: 3, desc: "受けたダメージをそのまま相手本体に反射する！" }
];
